### ISSUE TITLE
Automat data to use Biolink 2.1 preferred predicate

### ISSUE THREAD

**Issue by mmersmann** [RENCI-AUTOMAT/Automat-server#12]
1. Update SRI edge normalizer to be aware of preferred predicates ([see issue in EdgeNorm repo](https://github.com/TranslatorSRI/EdgeNormalization/issues/22))
2. All data in Automat can then be built using that

**Due:** July 1, 2021

**Comment by mmersmann** [comment]
**Update:** Will require an update to data ingest code. Shouldn't affect Automat/Strider/Ranking agent work. Dependent upon Biolink lookup service handling directions correctly. Phil and Chris currently working on this.

**Comment by PhillipsOwen** [comment]
The edge norm issue (https://github.com/TranslatorSRI/EdgeNormalization/issues/22) has been updated as complete. note biolink lookup now contains edge norm functionality.

in addition, biolink lookup now supports biolink model version 2..0. Chris has also updated biolink lookup to use canonical predicate directions.

no progress update on part 2 of this issue yet (AUTOMAT data update).

**Comment by mmersmann** [comment]
As Phil updates Platers, and pushes them to use 2.0 NN and Edge Norm, this will be complete. Will essentially happen with switch to Biolink 2.1 at the end of July.
