### ISSUE TITLE
KP Entity subclass semantic operations

### ISSUE THREAD

**Issue by mmersmann** [RENCI-AUTOMAT/Automat-server#13]
**Due:** July 15, 2021

**Comment by mmersmann** [comment]
@cbizon to discuss with @YaphetKG next week to determine next steps

**Comment by mmersmann** [comment]
@PhillipsOwen to continue discussion with @YaphetKG next week (July 12-16) to finalize next steps.

Summary of previous conversation: Taking ontology graphs, merging with graphs as we build them. (e.g., HMDB, merging in Chebi ontology to create new HMDB graph) Updating Transpiler to add optional subclass in query.

**Comment by mmersmann** [comment]
Update: Onto hierarchy graph built

Next Steps:
1. Filter nodes from edges
2. Merge with Plater graphs
3. Modify the Transpiler to query subclass subgraphs
4. Test (Chris)

**Comment by richakanwar13** [comment]
1&2 done.

[Issue](https://github.com/ranking-agent/reasoner-transpiler/issues/49) created for pt 3.

**Comment by richakanwar13** [comment]
Per meeting on 9/22, can be closed.
