### ISSUE TITLE
Remove 1.0 endpoints from the smartapi registry

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Automat-server#19]
From the faq:

To delete an API you must be the registered owner of that API. Log in to access the user dashboard and see a list of the APIs you have registered. Click on the delete button of the API you want to delete and follow the instructions to delete.

Looks like @YaphetKG is the proud owner of these...

**Comment by YaphetKG** [comment]
All Trapi 1.0 plater endpoints have been removed from smart api registry.

**Comment by YaphetKG** [comment]
All 1.1 endpoints are also removed. 
Closing this issue.
