### ISSUE TITLE
Add Operations to Automat

### ISSUE THREAD

**Issue by mmersmann** [RENCI-AUTOMAT/Automat-server#20]
Add:
1. connect k nodes
2. Annotation

**Comment by cbizon** [comment]
I think that these smartapi registrations are not correct.  We have:
```
"x-trapi": {
  "operation": [
     "lookup",
      "overlay_connect_knodes",
      "annotate_nodes"
    ],
  "version": "1.2.0"
}
```

But instead of "operation" it should be "operations" with an s.

**Comment by YaphetKG** [comment]
typo here is fixed.

**Comment by YaphetKG** [comment]
closing this as completed
