### ISSUE TITLE
Create Robokop Base

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Automat-server#21]
Robokop Base should include:

Biolink - latest parse installed in automat/plater on 8/17             
CTD - latest parse installed in automat/plater on 8/6            
DrugCentral - latest parse installed in automat/plater on 8/17
GtoPdb - latest parse installed in automat/plater on 8/6                  
Hetio - latest parse installed in automat/plater on 8/17
HGNC - latest parse installed in automat/plater on 8/17             
HMDB - latest parse installed in automat/plater on 8/6             
HumanGOA - latest parse installed in automat/plater on 8/6             
IntAct - latest parse installed in automat/plater on 8/6               
PANTHER - latest parse installed in automat/plater on 8/6             
PHAROS - latest parse installed in automat/plater on 8/17            
UberGraph - latest parse installed in automat/plater on 8/9    

When complete, get a copy to Kara Schatz

**Comment by YaphetKG** [comment]
Complete
