### ISSUE TITLE
TRAPI TIMELINE: KPs complete v1.2 implementations and registered in SmartAPI

### ISSUE THREAD

**Issue by mmersmann** [RENCI-AUTOMAT/Automat-server#24]
Includes Plater
**Due Date:** August 18

**Note:** 1.1 and 1.2 should run in parallel until we’re ready to shut off 1.1

[TRAPI 1.1 to 1.2 Change Log](https://github.com/NCATSTranslator/ReasonerAPI/pull/277/files).
[ReasonerAPI Reference Ticket](https://github.com/NCATSTranslator/ReasonerAPI/issues/271)

**Comment by richakanwar13** [comment]
Complete as per meeting on 9/3.
