### ISSUE TITLE
TRAPI 1.2 implementation: Verify registration, including uptime status:pass

### ISSUE THREAD

**Issue by richakanwar13** [RENCI-AUTOMAT/Automat-server#28]
Verify registration, including uptime status:pass [here](https://smart-api.info/registry/translator?tags=translator)

**Comment by YaphetKG** [comment]
Smart api registrations are ok. But on smart api for most of our endpoints we get uptime status "Unknown", even when there is examples that should return 200. Checking with smart api folks if this is something we need to fix on our side.

**Comment by YaphetKG** [comment]
Resolved by Smart api Folks (Chunlei)
