### ISSUE TITLE
Decide about multiple deployments

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Automat-server#30]
We are going to need multiple deployments of automat & its associated platers.  In the future (present?), these will run on ITRB systems.

In the near future (Nov 8) we would like to have 2 environments: dev and prod.

"prod" wlll be frozen until the demo (Dec 15) and "dev" will be modifiable.

Where these run is flexible.

If we don't want to change anything (data, code, etc) for 6 weeks or so, we can just point both dev and prod at the same automat.  But if we want the flexibility, then we need to have multiple deployments.  Or, I think we have some things getting close in ITRB, we could use that for one or the other of these.

We should decide this week on our strategy.

**Comment by YaphetKG** [comment]
Closing as we have multiple environments
