### ISSUE TITLE
Expose properties

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Automat-server#34]
I'm not sure if TRAPI has this yet, but we want to expose the node properties that node types have in our meta_knowledge_graph endpoints.  This will help with https://github.com/ranking-agent/strider/issues/287

**Comment by YaphetKG** [comment]
In [this PR](https://github.com/TranslatorSRI/Plater/pull/65) , node properties are computed for every node and the union of attribute sets of leaf nodes are presented in the meta kg graph.

Meta Kg node object has schema `attributes` property , the computed attributes are presented in this list. 

This implementation drops `id` and `name` attributes from the final schema attributes list as those are core attributes.
