### ISSUE TITLE
log4j vulnerability

### ISSUE THREAD

**Issue by richakanwar13** [RENCI-AUTOMAT/Automat-server#35]

**Comment by richakanwar13** [comment]
Yaphet has updated the AUTOMAT/PLATER deploys to use the neo4j image that corrects the log4j issue. 

robokopdb2, robokopkg , and covidkop instances still need to be updated.

**Comment by PhillipsOwen** [comment]
Yaphet patched the robokopdb2, robokopkg and covidkop instances to remove the neo4j vulnerability.

these instances will require neo4j version upgrades but they arent critical at this time.

**Comment by richakanwar13** [comment]
covidkop remains to be addressed.

**Comment by richakanwar13** [comment]
Yaphet indicates that covidkop is deployed on sterling/prod but not yet fully functional.

**Comment by YaphetKG** [comment]
Covidkop is moved to sterling and functional. Mitchell instance has been scaled down with all instances, freeing usage on the arrival node.

**Comment by richakanwar13** [comment]
Completed as per meeting on 2/16.
