### ISSUE TITLE
Lots of 504s

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Automat-server#5]
When running this query through strider:
```
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "id": "UniProtKB:P52788",
                    "category": "biolink:Gene"
                },
                "n1": {
                    "category": "biolink:ChemicalSubstance"
                }
            },
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1"
                }
            }
        }
    }
}
```

It is generating multiple Automat 504 errors:
504 Server Error: Gateway Time-out for url: https://automat.renci.org/kegg/reasonerapi (2 times)
504 Server Error: Gateway Time-out for url: https://automat.renci.org/cord19-scigraph/reasonerapi (4 times)
504 Server Error: Gateway Time-out for url: https://automat.renci.org/chembio/reasonerapi (2 times)

**Comment by YaphetKG** [comment]
I think this has to do with memory assigned for neo4j , need to bump up for all of the KP's specially those assigned 1G

**Comment by PhillipsOwen** [comment]
i can do this if you like. minimum of 4G all around? 8G?

**Comment by cbizon** [comment]
Seems to be working now.
